/**
 * Copyright (c) 2012, 2013, Andrea Funto'. All rights reserved.
 *
 * This file is part of the Strutlets framework ("Strutlets").
 *
 * Strutlets is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU Lesser General Public License as published by the Free 
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * Strutlets is distributed in the hope that it will be useful, but WITHOUT ANY 
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
 * A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more 
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License 
 * along with Strutlets. If not, see <http://www.gnu.org/licenses/>.
 */

package org.dihedron.webmvc.exceptions;


/**
 * An exception generated by the framework during the deployment phase, when it
 * creates the proxy and stub.
 *
 * @author Andrea Funto'
 */
public class DeploymentException extends WebMVCException {

    /**
     * Serial version id.
     */
    private static final long serialVersionUID = -3891772510619458168L;

    /**
     * Constructor.
     */
    public DeploymentException() {
    }

    /**
     * Constructor.
     *
     * @param message the exception message.
     */
    public DeploymentException(String message) {
        super(message);
    }

    /**
     * Constructor.
     *
     * @param cause the exception's root cause.
     */
    public DeploymentException(Throwable cause) {
        super(cause);
    }

    /**
     * Constructor.
     *
     * @param message the exception's message.
     * @param cause   the exception's root cause.
     */
    public DeploymentException(String message, Throwable cause) {
        super(message, cause);
    }

    /**
     * @param args
     */
    public static void main(String[] args) {
        // TODO Auto-generated method stub

    }
}
